---
- hosts: all
  sudo: true
  vars:
    project_path: /vagrant
    doc_root: /vagrant/public
    dbname: out_of_office
    dbuser: out_of_office
    dbpasswd: secret
    timezone: America/New_York
    server_name: "{{ ansible_eth1.ipv4.address }}"
    application_env: "local"
    apt_repositories: [ 'ppa:chris-lea/node.js' ]
    sys_packages: [ 'curl', 'vim', 'git', 'nodejs']
    php_packages: [ 'php5-curl', 'php5-cli', 'php5-mcrypt', 'php5-mysql', 'python-mysqldb', 'php-pear' ]
    pear_channels: [ 'pear.phing.info' ]
    pear_packages: [ 'phing/phing', 'PHP_CodeSniffer' ]
    npm_packages: [ 'coffee-script', 'node-sass', 'grunt-cli', 'grunt', 'bower' ]
  roles:
    - init
    - nginxphp
    - mysql
    - composer
    - npm