---
- name: Install Nginx
  apt: pkg=nginx state=latest

- name: Install php5-fpm
  apt: pkg=php5-fpm state=latest

- name: Change default nginx site
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: Install PHP Packages
  apt: pkg={{ item }} state=latest
  with_items: php_packages

- name: Discover PEAR channels
  command: pear channel-discover {{ item }}
  with_items: pear_channels
  register: pear_channel_result
  changed_when: "'initialized' not in pear_channel_result.stdout"
  failed_when: "'failed' in pear_channel_result.stdout"

- name: Install PEAR packages
  command: pear install {{ item }}
  with_items: pear_packages
  register: pear_package_result
  changed_when: "'is already installed' not in pear_package_result.stdout"
  failed_when:  "'No releases available for package' in pear_package_result.stdout"